"""add_material_traceability

Revision ID: f7cee2171e4d
Revises: 521e88e2a664
Create Date: 2026-05-15 08:15:03.784531+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7cee2171e4d'
down_revision: Union[str, Sequence[str], None] = '521e88e2a664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_traceability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_invoice_id', sa.Integer(), nullable=True),
    sa.Column('source_batch_id', sa.Integer(), nullable=True),
    sa.Column('source_product_id', sa.Integer(), nullable=False),
    sa.Column('internal_sale_id', sa.Integer(), nullable=True),
    sa.Column('slaughter_record_id', sa.Integer(), nullable=True),
    sa.Column('finished_product_id', sa.Integer(), nullable=True),
    sa.Column('finished_product_sale_id', sa.Integer(), nullable=True),
    sa.Column('trace_status', sa.String(length=20), nullable=False),
    sa.Column('source_weight_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('finished_weight_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('sold_weight_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finished_product_id'], ['slaughter_finished_products.id'], ),
    sa.ForeignKeyConstraint(['finished_product_sale_id'], ['finished_product_sales.id'], ),
    sa.ForeignKeyConstraint(['internal_sale_id'], ['whole_fish_sales.id'], ),
    sa.ForeignKeyConstraint(['slaughter_record_id'], ['daily_slaughter_records.id'], ),
    sa.ForeignKeyConstraint(['source_batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['source_invoice_id'], ['import_invoices.id'], ),
    sa.ForeignKeyConstraint(['source_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # 跳过：数据中存在 salesperson_id 不在 users 表中的情况
    # op.create_foreign_key(None, 'whole_fish_sales', 'users', ['salesperson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whole_fish_sales', type_='foreignkey')
    op.drop_table('material_traceability')
    # ### end Alembic commands ###
