"""simplify_return_items_and_add_eu_registration

Revision ID: 84a9da58c700
Revises: 4c7ad1a41fd1
Create Date: 2026-05-16 18:13:43.816559+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84a9da58c700'
down_revision: Union[str, Sequence[str], None] = '4c7ad1a41fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('eu_registration_no', sa.String(length=100), nullable=True))
    op.add_column('exchange_records', sa.Column('related_invoice_ids', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('return_items_product_id_fkey'), 'return_items', type_='foreignkey')
    op.drop_constraint(op.f('return_items_finished_product_sale_item_id_fkey'), 'return_items', type_='foreignkey')
    op.drop_constraint(op.f('return_items_whole_fish_sale_item_id_fkey'), 'return_items', type_='foreignkey')
    op.drop_column('return_items', 'product_name')
    op.drop_column('return_items', 'spec')
    op.drop_column('return_items', 'quantity')
    op.drop_column('return_items', 'reason_detail')
    op.drop_column('return_items', 'whole_fish_sale_item_id')
    op.drop_column('return_items', 'product_id')
    op.drop_column('return_items', 'finished_product_sale_item_id')
    op.drop_column('return_items', 'return_reason')
    op.add_column('return_orders', sa.Column('processing_plant_eu_no', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whole_fish_sales', type_='foreignkey')
    op.drop_column('return_orders', 'processing_plant_eu_no')
    op.add_column('return_items', sa.Column('return_reason', postgresql.ENUM('QUALITY_ISSUE', 'LOGISTICS_DAMAGE', 'SPEC_MISMATCH', 'TEMPERATURE_ISSUE', 'FOREIGN_MATTER', 'CUSTOMER_REASON', 'EXPIRED', 'OTHER', name='returnreason'), autoincrement=False, nullable=False))
    op.add_column('return_items', sa.Column('finished_product_sale_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('return_items', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('return_items', sa.Column('whole_fish_sale_item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('return_items', sa.Column('reason_detail', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('return_items', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('return_items', sa.Column('spec', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('return_items', sa.Column('product_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('return_items_whole_fish_sale_item_id_fkey'), 'return_items', 'whole_fish_sale_items', ['whole_fish_sale_item_id'], ['id'])
    op.create_foreign_key(op.f('return_items_finished_product_sale_item_id_fkey'), 'return_items', 'finished_product_sale_items', ['finished_product_sale_item_id'], ['id'])
    op.create_foreign_key(op.f('return_items_product_id_fkey'), 'return_items', 'products', ['product_id'], ['id'])
    op.drop_column('exchange_records', 'related_invoice_ids')
    op.drop_column('companies', 'eu_registration_no')
    # ### end Alembic commands ###
