"""add_warehouse_module_v2

Revision ID: 521e88e2a664
Revises: dff57fac17a5
Create Date: 2026-05-15 04:42:35.882483+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '521e88e2a664'
down_revision: Union[str, Sequence[str], None] = 'dff57fac17a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('WHOLE_PACKAGE', 'SUB_PACKAGE', 'ACCESSORY', 'BYPRODUCT', 'FINISHED', name='warehousetype'), nullable=False),
    sa.Column('business_scope', sa.Enum('IMPORT', 'DOMESTIC', 'ALL', name='warehousebusinessscope'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('product_unit_conversions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('from_unit', sa.String(length=20), nullable=False),
    sa.Column('to_unit', sa.String(length=20), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'from_unit', 'to_unit', name='uq_conversion_product_from_to')
    )
    op.create_table('stock_inbounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inbound_no', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_no', sa.String(length=100), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='stockstatus'), nullable=False),
    sa.Column('inbound_date', sa.Date(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inbound_no')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.Enum('INBOUND', 'OUTBOUND', 'TRANSFER_IN', 'TRANSFER_OUT', 'ADJUSTMENT', name='stockmovementtype'), nullable=False),
    sa.Column('movement_date', sa.Date(), nullable=False),
    sa.Column('qty_change', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('qty_before', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('qty_after', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ref_type', sa.String(length=50), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('ref_no', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_outbounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('outbound_no', sa.String(length=50), nullable=False),
    sa.Column('dest_type', sa.String(length=50), nullable=False),
    sa.Column('dest_id', sa.Integer(), nullable=True),
    sa.Column('dest_no', sa.String(length=100), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('outbound_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='stockstatus'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outbound_no')
    )
    op.create_table('stock_transfers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transfer_no', sa.String(length=50), nullable=False),
    sa.Column('from_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('to_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('from_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('from_unit', sa.String(length=20), nullable=False),
    sa.Column('to_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('to_unit', sa.String(length=20), nullable=False),
    sa.Column('conversion_ratio', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='stockstatus'), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_no')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('current_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reserved_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('available_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('warning_threshold', sa.Integer(), nullable=False),
    sa.Column('is_below_warning', sa.Boolean(), nullable=False),
    sa.Column('last_in_date', sa.Date(), nullable=True),
    sa.Column('last_out_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'product_id', 'batch_id', name='uq_stock_warehouse_product_batch')
    )
    # 跳过：数据中存在 salesperson_id 不在 users 表中的情况
    # op.create_foreign_key(None, 'whole_fish_sales', 'users', ['salesperson_id'], ['id'])

    # 初始化6个仓库
    from sqlalchemy.sql import table, column
    warehouses = table('warehouses',
        column('code'), column('name'), column('type'),
        column('business_scope'), column('is_active'), column('notes'),
        column('created_at'), column('updated_at')
    )
    op.bulk_insert(warehouses, [
        {'code':'ZB-IMPORT','name':'进口整包仓','type':'WHOLE_PACKAGE','business_scope':'IMPORT','is_active':True,'notes':'进口单证整鱼存储','created_at':'2026-05-15 00:00:00','updated_at':'2026-05-15 00:00:00'},
        {'code':'ZB-DOMESTIC','name':'国内整包仓','type':'WHOLE_PACKAGE','business_scope':'DOMESTIC','is_active':True,'notes':'国内采购整鱼存储','created_at':'2026-05-15 00:00:00','updated_at':'2026-05-15 00:00:00'},
        {'code':'FB-FISH','name':'分包仓（整鱼）','type':'SUB_PACKAGE','business_scope':'ALL','is_active':True,'notes':'整鱼分包后单条存储','created_at':'2026-05-15 00:00:00','updated_at':'2026-05-15 00:00:00'},
        {'code':'FB-SHRIMP','name':'分包仓（甜虾）','type':'SUB_PACKAGE','business_scope':'ALL','is_active':True,'notes':'甜虾分包后板/只存储','created_at':'2026-05-15 00:00:00','updated_at':'2026-05-15 00:00:00'},
        {'code':'FL-MATERIAL','name':'辅料仓','type':'ACCESSORY','business_scope':'ALL','is_active':True,'notes':'包装物/消耗品存储','created_at':'2026-05-15 00:00:00','updated_at':'2026-05-15 00:00:00'},
        {'code':'BY-PRODUCT','name':'副产品仓','type':'BYPRODUCT','business_scope':'ALL','is_active':True,'notes':'鱼头/鱼尾/鱼骨/边角料存储','created_at':'2026-05-15 00:00:00','updated_at':'2026-05-15 00:00:00'},
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whole_fish_sales', type_='foreignkey')
    op.drop_table('stocks')
    op.drop_table('stock_transfers')
    op.drop_table('stock_outbounds')
    op.drop_table('stock_movements')
    op.drop_table('stock_inbounds')
    op.drop_table('product_unit_conversions')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
