"""add slaughter source fields and finished product output

Revision ID: dff57fac17a5
Revises: 407690b56fc8
Create Date: 2026-05-15 03:31:40.428759+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dff57fac17a5'
down_revision: Union[str, Sequence[str], None] = '407690b56fc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slaughter_finished_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slaughter_record_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=True),
    sa.Column('produced_weight_kg', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('produced_quantity', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_stocked', sa.Boolean(), nullable=False),
    sa.Column('stock_inbound_id', sa.Integer(), nullable=True),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.Column('sold_weight_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('sold_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['slaughter_record_id'], ['daily_slaughter_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('bank_accounts', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('bank_accounts', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'public'::character varying"))
    op.alter_column('bank_accounts', 'current_balance',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('bank_accounts_account_number_not_empty_idx'), table_name='bank_accounts', postgresql_where="((account_number IS NOT NULL) AND ((account_number)::text <> ''::text))")
    op.create_unique_constraint(None, 'bank_accounts', ['code'])
    op.create_unique_constraint(None, 'bank_accounts', ['account_number'])
    op.create_foreign_key(None, 'bank_accounts', 'companies', ['company_id'], ['id'])
    op.alter_column('batches', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('brands', 'is_oem',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('brands', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_foreign_key(None, 'clearance_costs', 'companies', ['customs_broker_id'], ['id'])
    op.alter_column('commission_records', 'weight_kg',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('commission_records', 'commission_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=False)
    op.alter_column('companies', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'CNY'::character varying"))
    op.add_column('daily_slaughter_records', sa.Column('source_sale_id', sa.Integer(), nullable=True))
    op.add_column('daily_slaughter_records', sa.Column('source_batch_id', sa.Integer(), nullable=True))
    op.add_column('daily_slaughter_records', sa.Column('source_invoice_id', sa.Integer(), nullable=True))
    op.add_column('daily_slaughter_records', sa.Column('source_detail', sa.JSON(), nullable=True))
    op.add_column('daily_slaughter_records', sa.Column('cost_calculation_method', sa.String(length=20), nullable=False))
    op.add_column('daily_slaughter_records', sa.Column('auto_byproduct', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'daily_slaughter_records', 'import_invoices', ['source_invoice_id'], ['id'])
    op.create_foreign_key(None, 'daily_slaughter_records', 'batches', ['source_batch_id'], ['id'])
    op.create_foreign_key(None, 'daily_slaughter_records', 'whole_fish_sales', ['source_sale_id'], ['id'])
    op.alter_column('import_invoices', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('import_invoices', 'is_master',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('material_suppliers', 'min_order_qty',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('material_suppliers', 'lead_time_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('material_suppliers', 'is_preferred',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('material_suppliers_material_id_supplier_id_key'), 'material_suppliers', type_='unique')
    op.create_unique_constraint('uix_material_supplier', 'material_suppliers', ['material_id', 'supplier_id'])
    op.alter_column('product_templates', 'unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'kg'::character varying"))
    op.alter_column('product_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('product_variants', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('product_variants_template_id_brand_id_key'), 'product_variants', type_='unique')
    op.drop_column('products', 'brand')
    op.create_foreign_key(None, 'sales_receipts', 'transaction_records', ['transaction_id'], ['id'])
    op.alter_column('salespersons', 'commission_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=False)
    op.alter_column('template_boms', 'unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'个'::character varying"))
    op.alter_column('template_packagings', 'unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'个'::character varying"))
    op.alter_column('template_parts', 'boxes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('template_parts', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_transaction_records_related_sale_ids_gin'), table_name='transaction_records', postgresql_using='gin')
    op.alter_column('transaction_records', 'related_sale_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('variant_accessories', 'unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'个'::character varying"))
    op.alter_column('variant_accessories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('variant_accessories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('variant_packagings', 'unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'个'::character varying"))
    op.alter_column('variant_packagings', 'is_override',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('variant_packagings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('variant_packagings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('whole_fish_sales_salesperson_id_fkey'), 'whole_fish_sales', type_='foreignkey')
    # 跳过：数据中存在 salesperson_id=2 不在 users 表中，先保留原外键
    # op.create_foreign_key(None, 'whole_fish_sales', 'users', ['salesperson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whole_fish_sales', type_='foreignkey')
    op.create_foreign_key(op.f('whole_fish_sales_salesperson_id_fkey'), 'whole_fish_sales', 'salespersons', ['salesperson_id'], ['id'], ondelete='SET NULL')
    op.alter_column('variant_packagings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('variant_packagings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('variant_packagings', 'is_override',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('variant_packagings', 'unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'个'::character varying"))
    op.alter_column('variant_accessories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('variant_accessories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('variant_accessories', 'unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'个'::character varying"))
    op.create_index(op.f('ix_transaction_records_related_sale_ids_gin'), 'transaction_records', ['related_sale_ids'], unique=False, postgresql_using='gin')
    op.alter_column('transaction_records', 'related_sale_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('template_parts', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('template_parts', 'boxes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('template_packagings', 'unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'个'::character varying"))
    op.alter_column('template_boms', 'unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'个'::character varying"))
    op.alter_column('salespersons', 'commission_rate',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.drop_constraint(None, 'sales_receipts', type_='foreignkey')
    op.add_column('products', sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('product_variants_template_id_brand_id_key'), 'product_variants', ['template_id', 'brand_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('product_variants', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('product_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('product_templates', 'unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'kg'::character varying"))
    op.drop_constraint('uix_material_supplier', 'material_suppliers', type_='unique')
    op.create_unique_constraint(op.f('material_suppliers_material_id_supplier_id_key'), 'material_suppliers', ['material_id', 'supplier_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('material_suppliers', 'is_preferred',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('material_suppliers', 'lead_time_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('material_suppliers', 'min_order_qty',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('import_invoices', 'is_master',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('import_invoices', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'daily_slaughter_records', type_='foreignkey')
    op.drop_constraint(None, 'daily_slaughter_records', type_='foreignkey')
    op.drop_constraint(None, 'daily_slaughter_records', type_='foreignkey')
    op.drop_column('daily_slaughter_records', 'auto_byproduct')
    op.drop_column('daily_slaughter_records', 'cost_calculation_method')
    op.drop_column('daily_slaughter_records', 'source_detail')
    op.drop_column('daily_slaughter_records', 'source_invoice_id')
    op.drop_column('daily_slaughter_records', 'source_batch_id')
    op.drop_column('daily_slaughter_records', 'source_sale_id')
    op.alter_column('companies', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'CNY'::character varying"))
    op.alter_column('commission_records', 'commission_rate',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('commission_records', 'weight_kg',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'clearance_costs', type_='foreignkey')
    op.alter_column('brands', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('brands', 'is_oem',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('batches', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'bank_accounts', type_='foreignkey')
    op.drop_constraint(None, 'bank_accounts', type_='unique')
    op.drop_constraint(None, 'bank_accounts', type_='unique')
    op.create_index(op.f('bank_accounts_account_number_not_empty_idx'), 'bank_accounts', ['account_number'], unique=True, postgresql_where="((account_number IS NOT NULL) AND ((account_number)::text <> ''::text))")
    op.alter_column('bank_accounts', 'current_balance',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('bank_accounts', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'public'::character varying"))
    op.alter_column('bank_accounts', 'code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_table('slaughter_finished_products')
    # ### end Alembic commands ###
