"""add_salesperson_and_commission

Revision ID: 72d0c5ffb1a3
Revises: 7f74e65b9d5d
Create Date: 2026-05-01 09:45:54.674406+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d0c5ffb1a3'
down_revision: Union[str, Sequence[str], None] = '7f74e65b9d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
