"""add items_per_box and purchase_order_box_fields

Revision ID: 368caa333c50
Revises: cfe0bab44a74
Create Date: 2026-05-26 16:32:55.598074+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '368caa333c50'
down_revision: Union[str, Sequence[str], None] = 'cfe0bab44a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'eu_registration_no')
    op.drop_constraint(op.f('fk_receipts_sale_v2'), 'finished_product_receipts', type_='foreignkey')
    op.drop_constraint(op.f('fk_receipts_transaction'), 'finished_product_receipts', type_='foreignkey')
    op.create_foreign_key(None, 'finished_product_receipts', 'finished_product_sales_v2', ['sale_v2_id'], ['id'])
    op.create_foreign_key(None, 'finished_product_receipts', 'transaction_records', ['transaction_id'], ['id'])
    op.alter_column('finished_product_sales_v2', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('material_categories', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('material_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('material_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('material_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('product_series', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_series', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('product_series', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('product_series', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('product_specs', 'portion_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_specs', 'box_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_specs', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_specs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('product_specs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('product_specs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_product_specs_template_id'), table_name='product_specs')
    op.alter_column('product_variants', 'template_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_product_variants_spec_id'), table_name='product_variants')
    op.drop_constraint(op.f('fk_variants_spec'), 'product_variants', type_='foreignkey')
    op.create_foreign_key(None, 'product_variants', 'product_specs', ['spec_id'], ['id'], ondelete='CASCADE')
    op.add_column('products', sa.Column('items_per_box', sa.Integer(), nullable=True))
    op.drop_index(op.f('idx_products_material_category_id'), table_name='products', postgresql_where="((category)::text = 'bom_material'::text)")
    op.drop_constraint(op.f('uq_products_code'), 'products', type_='unique')
    op.drop_index(op.f('idx_popv2_material_id'), table_name='purchase_order_products_v2')
    op.drop_constraint(op.f('fk_popv2_material'), 'purchase_order_products_v2', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_order_products_v2', 'products', ['material_id'], ['id'])
    op.drop_constraint(op.f('fk_return_orders_finished_sale_v2'), 'return_orders', type_='foreignkey')
    op.create_foreign_key(None, 'return_orders', 'finished_product_sales_v2', ['finished_product_sale_v2_id'], ['id'])
    op.alter_column('template_boms', 'material_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'salmon'::character varying"))
    op.alter_column('template_boms', 'is_main',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('variant_accessories', 'accessory_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'accessory'::character varying"))
    op.alter_column('variant_price_tiers', 'min_qty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('variant_price_tiers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('variant_price_tiers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('variant_price_tiers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_variant_price_tiers_variant_id'), table_name='variant_price_tiers')
    op.add_column('warehouse_purchase_orders', sa.Column('actual_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('warehouse_purchase_orders', sa.Column('box_count', sa.Integer(), nullable=True))
    op.add_column('warehouse_purchase_orders', sa.Column('items_per_box', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'whole_fish_sales', 'users', ['salesperson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whole_fish_sales', type_='foreignkey')
    op.drop_column('warehouse_purchase_orders', 'items_per_box')
    op.drop_column('warehouse_purchase_orders', 'box_count')
    op.drop_column('warehouse_purchase_orders', 'actual_amount')
    op.create_index(op.f('ix_variant_price_tiers_variant_id'), 'variant_price_tiers', ['variant_id'], unique=False)
    op.alter_column('variant_price_tiers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('variant_price_tiers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('variant_price_tiers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('variant_price_tiers', 'min_qty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('variant_accessories', 'accessory_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'accessory'::character varying"))
    op.alter_column('template_boms', 'is_main',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('template_boms', 'material_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'salmon'::character varying"))
    op.drop_constraint(None, 'return_orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_return_orders_finished_sale_v2'), 'return_orders', 'finished_product_sales_v2', ['finished_product_sale_v2_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'purchase_order_products_v2', type_='foreignkey')
    op.create_foreign_key(op.f('fk_popv2_material'), 'purchase_order_products_v2', 'products', ['material_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_popv2_material_id'), 'purchase_order_products_v2', ['material_id'], unique=False)
    op.create_unique_constraint(op.f('uq_products_code'), 'products', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_products_material_category_id'), 'products', ['material_category_id'], unique=False, postgresql_where="((category)::text = 'bom_material'::text)")
    op.drop_column('products', 'items_per_box')
    op.drop_constraint(None, 'product_variants', type_='foreignkey')
    op.create_foreign_key(op.f('fk_variants_spec'), 'product_variants', 'product_specs', ['spec_id'], ['id'])
    op.create_index(op.f('ix_product_variants_spec_id'), 'product_variants', ['spec_id'], unique=False)
    op.alter_column('product_variants', 'template_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_product_specs_template_id'), 'product_specs', ['template_id'], unique=False)
    op.alter_column('product_specs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('product_specs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('product_specs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('product_specs', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product_specs', 'box_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product_specs', 'portion_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product_series', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('product_series', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('product_series', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('product_series', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('material_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('material_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('material_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('material_categories', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('finished_product_sales_v2', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_constraint(None, 'finished_product_receipts', type_='foreignkey')
    op.drop_constraint(None, 'finished_product_receipts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_receipts_transaction'), 'finished_product_receipts', 'transaction_records', ['transaction_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_receipts_sale_v2'), 'finished_product_receipts', 'finished_product_sales_v2', ['sale_v2_id'], ['id'], ondelete='CASCADE')
    op.add_column('companies', sa.Column('eu_registration_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
