"""add sale_id to purchase_orders_v2 for sale-driven-procurement

Revision ID: 4e36257a8e47
Revises: 84a9da58c700
Create Date: 2026-05-22 23:57:01.778302+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e36257a8e47'
down_revision: Union[str, Sequence[str], None] = '84a9da58c700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders_v2', sa.Column('sale_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_purchase_orders_v2_sale_id'), 'purchase_orders_v2', ['sale_id'], unique=False)
    op.drop_column('companies', 'eu_registration_no')
    op.alter_column('finished_product_sales_v2', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_foreign_key(None, 'whole_fish_sales', 'users', ['salesperson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whole_fish_sales', type_='foreignkey')
    op.alter_column('finished_product_sales_v2', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.add_column('companies', sa.Column('eu_registration_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_purchase_orders_v2_sale_id'), table_name='purchase_orders_v2')
    op.drop_column('purchase_orders_v2', 'sale_id')
    # ### end Alembic commands ###
