"""add parent_invoice_id and is_master to import_invoices

Revision ID: 038481c48154
Revises: 61a295fcd54e
Create Date: 2026-05-05 14:29:56.721395+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '038481c48154'
down_revision: Union[str, Sequence[str], None] = '61a295fcd54e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_slaughter_records', 'byproduct_head_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'byproduct_tail_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'byproduct_bone_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'byproduct_trim_weight_kg',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'loss_weight_kg',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'loss_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'meat_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'cost_price_per_kg',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'total_cost',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'cost_source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'auto'::character varying"))
    op.alter_column('daily_slaughter_records', 'available_meat_kg',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'sold_meat_kg',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('daily_slaughter_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('daily_slaughter_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_slaughter_date'), table_name='daily_slaughter_records')
    op.drop_index(op.f('idx_slaughter_type'), table_name='daily_slaughter_records')
    op.create_index(op.f('ix_daily_slaughter_records_slaughter_date'), 'daily_slaughter_records', ['slaughter_date'], unique=False)
    op.alter_column('finished_product_commissions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('finished_product_commissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('finished_product_commissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('finished_product_sale_items', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('finished_product_sale_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('finished_product_sale_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_fps_item_product_id'), table_name='finished_product_sale_items')
    op.drop_index(op.f('idx_fps_item_sale_id'), table_name='finished_product_sale_items')
    op.drop_column('finished_product_sales', 'slaughter_date')
    op.add_column('import_invoices', sa.Column('parent_invoice_id', sa.Integer(), nullable=True))
    op.add_column('import_invoices', sa.Column('is_master', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    op.create_foreign_key(None, 'import_invoices', 'import_invoices', ['parent_invoice_id'], ['id'])
    op.alter_column('loss_records', 'weight_kg',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('loss_records', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('loss_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('loss_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_loss_date'), table_name='loss_records')
    op.drop_index(op.f('idx_loss_type'), table_name='loss_records')
    op.alter_column('product_accessories', 'unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'个'::character varying"))
    op.alter_column('product_accessories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('product_accessories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('product_accessories_product_id_fkey'), 'product_accessories', type_='foreignkey')
    op.drop_constraint(op.f('product_accessories_accessory_id_fkey'), 'product_accessories', type_='foreignkey')
    op.create_foreign_key(None, 'product_accessories', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'product_accessories', 'products', ['accessory_id'], ['id'])
    op.drop_column('products', 'safety_buffer')
    op.drop_column('products', 'avg_daily_consumption')
    op.drop_column('products', 'stock_weight_kg')
    op.alter_column('warehouse_purchase_orders', 'unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'kg'::character varying"))
    op.alter_column('warehouse_purchase_orders', 'lead_time_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('warehouse_purchase_orders', 'warehouse_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'finished'::character varying"))
    op.alter_column('warehouse_purchase_orders', 'inbound_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'purchase'::character varying"))
    op.alter_column('warehouse_purchase_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('warehouse_purchase_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_wpo_order_date'), table_name='warehouse_purchase_orders')
    op.drop_index(op.f('idx_wpo_product_id'), table_name='warehouse_purchase_orders')
    op.alter_column('warehouse_stocks', 'warehouse_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'finished'::character varying"))
    op.alter_column('warehouse_stocks', 'current_quantity',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('warehouse_stocks', 'reserved_quantity',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('warehouse_stocks', 'available_quantity',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('warehouse_stocks', 'is_below_warning',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('warehouse_stocks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('warehouse_stocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('whole_fish_sales', 'sale_no',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whole_fish_sales', 'sale_no',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('warehouse_stocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('warehouse_stocks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('warehouse_stocks', 'is_below_warning',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('warehouse_stocks', 'available_quantity',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('warehouse_stocks', 'reserved_quantity',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('warehouse_stocks', 'current_quantity',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('warehouse_stocks', 'warehouse_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'finished'::character varying"))
    op.create_index(op.f('idx_wpo_product_id'), 'warehouse_purchase_orders', ['product_id'], unique=False)
    op.create_index(op.f('idx_wpo_order_date'), 'warehouse_purchase_orders', ['order_date'], unique=False)
    op.alter_column('warehouse_purchase_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('warehouse_purchase_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('warehouse_purchase_orders', 'inbound_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'purchase'::character varying"))
    op.alter_column('warehouse_purchase_orders', 'warehouse_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'finished'::character varying"))
    op.alter_column('warehouse_purchase_orders', 'lead_time_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('warehouse_purchase_orders', 'unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'kg'::character varying"))
    op.add_column('products', sa.Column('stock_weight_kg', sa.NUMERIC(precision=12, scale=3), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('avg_daily_consumption', sa.NUMERIC(precision=12, scale=4), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('safety_buffer', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product_accessories', type_='foreignkey')
    op.drop_constraint(None, 'product_accessories', type_='foreignkey')
    op.create_foreign_key(op.f('product_accessories_accessory_id_fkey'), 'product_accessories', 'products', ['accessory_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('product_accessories_product_id_fkey'), 'product_accessories', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('product_accessories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('product_accessories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('product_accessories', 'unit',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'个'::character varying"))
    op.create_index(op.f('idx_loss_type'), 'loss_records', ['loss_type'], unique=False)
    op.create_index(op.f('idx_loss_date'), 'loss_records', ['loss_date'], unique=False)
    op.alter_column('loss_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('loss_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('loss_records', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('loss_records', 'weight_kg',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'import_invoices', type_='foreignkey')
    op.drop_column('import_invoices', 'is_master')
    op.drop_column('import_invoices', 'parent_invoice_id')
    op.add_column('finished_product_sales', sa.Column('slaughter_date', sa.DATE(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_fps_item_sale_id'), 'finished_product_sale_items', ['sale_id'], unique=False)
    op.create_index(op.f('idx_fps_item_product_id'), 'finished_product_sale_items', ['product_id'], unique=False)
    op.alter_column('finished_product_sale_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('finished_product_sale_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('finished_product_sale_items', 'amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('finished_product_commissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('finished_product_commissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('finished_product_commissions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_daily_slaughter_records_slaughter_date'), table_name='daily_slaughter_records')
    op.create_index(op.f('idx_slaughter_type'), 'daily_slaughter_records', ['slaughter_type'], unique=False)
    op.create_index(op.f('idx_slaughter_date'), 'daily_slaughter_records', ['slaughter_date'], unique=False)
    op.alter_column('daily_slaughter_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('daily_slaughter_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('daily_slaughter_records', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('daily_slaughter_records', 'sold_meat_kg',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'available_meat_kg',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'cost_source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'auto'::character varying"))
    op.alter_column('daily_slaughter_records', 'total_cost',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'cost_price_per_kg',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'meat_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'loss_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'loss_weight_kg',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'byproduct_trim_weight_kg',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'byproduct_bone_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'byproduct_tail_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('daily_slaughter_records', 'byproduct_head_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
