"""add_invoice_cost_fields

Revision ID: 01db638ad219
Revises: 4db1003f4f48
Create Date: 2026-04-30 22:46:43.310117+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01db638ad219'
down_revision: Union[str, Sequence[str], None] = '4db1003f4f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_invoices', sa.Column('unit_price_usd', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('import_invoices', sa.Column('estimated_exchange_rate', sa.Numeric(precision=10, scale=6), nullable=True))
    op.add_column('import_invoices', sa.Column('estimated_cost_cny', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('import_invoices', sa.Column('actual_cost_cny', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_invoices', 'actual_cost_cny')
    op.drop_column('import_invoices', 'estimated_cost_cny')
    op.drop_column('import_invoices', 'estimated_exchange_rate')
    op.drop_column('import_invoices', 'unit_price_usd')
    # ### end Alembic commands ###
